# Site settings
name: Just for recording
email: caojian_1104@126.com
author: CC-2018
url: https://cc2018.github.io/cc2018
github: https://github.com/cc2018/cc2018
baseurl: ""
description: 做一个自我要求的阅读者。
meta_description: personal blog;
motto: 千古兴亡多少事, 不尽长江滚滚流

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10
plugins: [jekyll-paginate]

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: cc2018
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: ff1da0dd6c6a814ef6ec49dd10246092
